global:
  scrape_interval: 15s

scrape_configs:

  - job_name: "ecs-sales-app"

    metrics_path: /metrics

    static_configs:
      - targets:
          - sales-app-alb-1496073499.ap-southeast-1.elb.amazonaws.com
          